name: choco_bliss_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  printing: ^5.9.0
  pdf: ^3.6.0
  image_picker: ^1.1.2
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.1
  change_app_package_name: ^1.3.0
  firebase_app_check: ^0.3.1+2
  cached_network_image: ^3.4.1

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

