// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnivI3kXLX1qXQRzN67fw5Bf3rjzhc1a0',
    appId: '1:419858186358:web:f4b1d98e236644fd4adf57',
    messagingSenderId: '419858186358',
    projectId: 'chocobliss-e2bc5',
    authDomain: 'chocobliss-e2bc5.firebaseapp.com',
    databaseURL: 'https://chocobliss-e2bc5-default-rtdb.firebaseio.com',
    storageBucket: 'chocobliss-e2bc5.appspot.com',
    measurementId: 'G-ZXK2MLCD8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-9LsysDnSVbCfLKE33cjNzl7un0tD8FU',
    appId: '1:419858186358:android:e152167049d3fc814adf57',
    messagingSenderId: '419858186358',
    projectId: 'chocobliss-e2bc5',
    databaseURL: 'https://chocobliss-e2bc5-default-rtdb.firebaseio.com',
    storageBucket: 'chocobliss-e2bc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8GdPL3MmC10j-p_I39EjHJTex8YqaEqk',
    appId: '1:419858186358:ios:3db76fe5f2704f144adf57',
    messagingSenderId: '419858186358',
    projectId: 'chocobliss-e2bc5',
    databaseURL: 'https://chocobliss-e2bc5-default-rtdb.firebaseio.com',
    storageBucket: 'chocobliss-e2bc5.appspot.com',
    iosBundleId: 'com.chocoBlissUk.chocoBlissMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8GdPL3MmC10j-p_I39EjHJTex8YqaEqk',
    appId: '1:419858186358:ios:3db76fe5f2704f144adf57',
    messagingSenderId: '419858186358',
    projectId: 'chocobliss-e2bc5',
    databaseURL: 'https://chocobliss-e2bc5-default-rtdb.firebaseio.com',
    storageBucket: 'chocobliss-e2bc5.appspot.com',
    iosBundleId: 'com.chocoBlissUk.chocoBlissMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnivI3kXLX1qXQRzN67fw5Bf3rjzhc1a0',
    appId: '1:419858186358:web:d2119c65ff2c2f444adf57',
    messagingSenderId: '419858186358',
    projectId: 'chocobliss-e2bc5',
    authDomain: 'chocobliss-e2bc5.firebaseapp.com',
    databaseURL: 'https://chocobliss-e2bc5-default-rtdb.firebaseio.com',
    storageBucket: 'chocobliss-e2bc5.appspot.com',
    measurementId: 'G-L58PCGVY25',
  );

}